stages:
- build_app
- test_app
- publish_app
- build_image
- publish_image

variables:
  npm_config_registry: https://services.ub.uni-leipzig.de/nexus/repository/npm/

npm_install:
  stage: build_app
  image:
    name: node:8-alpine
    entrypoint: ["/bin/su", "node", "-c"]
  script:
    - test -d .npm && mv .npm ${HOME}
    - npm run build
    - mv ${HOME}/.npm .
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm
    - lib
    - node_modules
    - public
    - test
  tags:
    - docker

npm_ci:
  stage: test_app
  image:
    name: node:8-alpine
    entrypoint: ["/bin/su", "node", "-c"]
  script:
  - npm run ci
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm
    - lib
    - public
  tags:
    - docker

npm_publish:
  stage: publish_app
  only:
  - master
  image:
    name: node:8-alpine
    entrypoint: ["/bin/su", "node", "-c"]
  script:
  - 'echo "//services.ub.uni-leipzig.de/nexus/repository/npm-ubl/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
  - npm publish
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm
  tags:
    - docker

docker_build:
  stage: build_image
  only:
  - master
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
  - docker build --no-cache --pull -t services.ub.uni-leipzig.de:11443/bdd_dev/dacap:latest .
  - docker tag services.ub.uni-leipzig.de:11443/bdd_dev/dacap:latest services.ub.uni-leipzig.de:11443/bdd_dev/dacap:${CI_PIPELINE_ID}
  - docker push services.ub.uni-leipzig.de:11443/bdd_dev/dacap:${CI_PIPELINE_ID}
  - docker push services.ub.uni-leipzig.de:11443/bdd_dev/dacap:latest
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm
  tags:
    - docker
