version: '2'
services:
  node:
    image: smoebody/dev-nodejs:10
    volumes:
      - ./:/app:z
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:9229:9229
    environment:
      npm_config_cache: /app/.npm
      NODE_ENV: development
      DEBUG: '*'
      user: admin
      password: adminpw
      strip_path: "false"
      proxy_url: http://localhost:3000/
    command:
      - npm run watch-inspect
